### ISSUE TITLE
Q: Why/how is this a "fuzzer"?

### ISSUE THREAD

**Issue by ppseprus** [Ganapati/FlipFrid#1]
Hey @Ganapati,

I have a limited knowledge on fuzzing, but my understanding is that it should be a feedback look. The fuzzer monitors the behaviour of the system its testing.
Im not really good with C++, but this app seems to perform dict attacks. Do I get that right? Am I missing something?

Btw. I like the app regardless. I was already [looking for a possibility](https://github.com/flipperdevices/flipperzero-firmware/issues/1587) to send signals faster — although, I had a different solution in mind and for SubGHz, not RFID.

Thanks,
Peter

**Comment by Ganapati** [comment]
Initially, flipfrid generated incorrect messages (wrong crc, wrong size) in order to test the reaction of the readers and to identify implementation problems.
With time, I realized that this was not really useful and that for this kind of analysis, the proxmark is much more suitable. So there is still the dictionary side but also the customer id bf, the existing card alteration... it still looks a bit like a fuzzer :)

Translated with www.DeepL.com/Translator (free version)

**Comment by ppseprus** [comment]
Ah! I see! Thanks for clarifying it to me! 🙇‍♂️
